import {Contact} from "./contact";

/**
 * @classdesc Class used to store all the information for a crew member. It also contains information on if a given crew member is responsible for their given
 * category. This necessitates that crewMember objects get created on a per event basis.
 * @see {Contact}
 */
export class CrewMember extends Contact {

    /**
     *
     * @param {int}crewID
     * The ID for the crew member, generated by the database
     * @param {int}contactID
     * The ID for the contact object info for the crew member
     * @param {String}description
     * The description of the crew member
     * @param {int}crewCategoryID
     * The ID for the crew category for the crew member
     * @param {String}crewCategoryName
     * The name for the crew category for the crew member.
     * @param {String}contactName
     * The name of the contact.
     * @param {String}phone
     * The phone nr. of the contact.
     * @param {String}email
     * The mail of the contact.
     * @param {boolean}isResponsible
     * If the crew member is responsible for their given category.
     * @param {boolean}contractSigned
     * If the contract for the crew member has been signed.
     * @param {boolean}hasBeenPaid
     * If the crew member has been paid.
     */
    constructor(crewID, contactID, description, crewCategoryID, crewCategoryName, contactName, phone, email, isResponsible, contractSigned, hasBeenPaid){
        super(contactID, contactName, phone, email);
        this.crewID = crewID;
        this.description = description;
        this.crewCategoryID = crewCategoryID;
        this.crewCategoryName = crewCategoryName;
        this.isResponsible = isResponsible;
        this.contractSigned = contractSigned;
        this.hasBeenPaid = hasBeenPaid;
    }
/*
    addCrewCategory(category) {
        this.crewCategories.push(category);
    }*/

    static getTestCrewMember(){
        let crewMemberOne = new CrewMember(0, super.getTestContacts()[3].contactID, 'This lazy dude can only work every third sunday when theres a full moon',
            0, "Lazy work", super.getTestContacts()[3].contactName, super.getTestContacts()[3].phone, super.getTestContacts()[3].email, false, false, false);
        return [crewMemberOne];
    }
}