/**
 * @classdesc Class used to store all the information relating to a document.
 */
export class Document{

    /**
     *
     * @param {int}documentID
     * The ID of the document, generated by the database.
     * @param {int}eventID
     * The ID of the event the document is associated with.
     * @param {String}documentName
     * The name of the document.
     * @param {String}documentLink
     * The link to the document.
     * @param {int}artistID
     * If the document is associated with an artist, the artist ID gets stored here.
     * @param {int}crewID
     * If the document is associated with a crew member, the crew member ID gets stored here.
     * @param {int}documentCategoryID
     * The ID of the category for the document.
     */
    constructor(documentID, eventID, documentName, documentLink, artistID, crewID, documentCategoryID){
        this.documentID = documentID;
        this.eventID = eventID;
        this.documentName = documentName;
        this.documentLink = documentLink;
        this.artistID = artistID;
        this.crewID = crewID;
        this.documentCategoryID = documentCategoryID;
    }

    static getTestDocuments(){
        let documentOne = new Document(0, 1,'artistContract.pdf',"Link here", null, null, 1);
        let documentTwo = new Document(1, 2,'test.pdf',"Link here", null, 1, 2);
        let documentThree = new Document(2, 3,'fan.pdf',"Link here", 1, null, 3);
        return [documentOne, documentTwo, documentThree];
    }
}