import {Organizer} from "./organizer";
import {Artist} from "./artist";
import {RiderElement} from "./riderElement";


/**
 * @classdesc The central class for the app. This class contains all the information for an event.
 */
export class Event {

    /**
     *
     * @param {int}eventID
     * The ID of the event. Generated by the database.
     * @param {String}eventName
     * The name of the event.
     * @param {String}startDate
     * The starting date of the event (yyyy-mm-dd)
     * @param {String}endDate
     * The end date of the event (yyyy-mm-dd)
     * @param {String}startTime
     * The starting time of the event (hh:mm)
     * @param {String}endTime
     * The end time of the event (hh:mm)
     * @param {String}address
     * The address for the event
     * @param {String}town
     * The town where the event is being held
     * @param {int}zipCode
     * The zipcode for the event addresss
     * @param {int}status
     * The ID of the status of the event (0 = under planning, 1 = published, 2 = archived, 3 = canceled)
     * @param {String}description
     * A description of the event
     * @param {String}publishDate
     * The publishing date of the event (yyyy-mm-dd)
     * @param {String}publishTime
     * The time of publishing for the event (hh:mm)
     * @param {Organizer}organizer
     * The organizer object responsible for the event
     * @param {int}eventType
     * The type of event, represented by an ID. The event types are static and fetched from the database during start-up and saved in EventStore.
     * @see EventStore
     * @param {PictureElement}picture
     * A picture element of the header picture for the event.
     */
    constructor(eventID, eventName, startDate, endDate, startTime, endTime, address, town, zipCode, status, description,
                publishDate, publishTime, organizer, eventType, picture) {
        this.eventID = eventID;
        this.eventName = eventName;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startTime = startTime;
        this.endTime = endTime;
        this.address = address;
        this.town = town;
        this.zipCode = zipCode;
        this.status = status;
        this.description = description;
        this.publishDate = publishDate;
        this.publishTime = publishTime;
        this.organizer = organizer;
        this.eventType = eventType;
        this.picture = picture;

        this.tickets = [];
        this.documents = [];
        this.crewMembers = [];
        this.crewCategories = [];
        this.artists = [];
        this.riderElements = [];
    }

    addTicketType(ticketType) {
        this.tickets.push(ticketType);
    }

    addDocument(document) {
        this.documents.push(document);
    }

    addCrewMember(crewMember) {
        this.crewMembers.push(crewMember);
    }

    addCrewCategory(crewCategory) {
        this.crewCategories.push(crewCategory);
    }

    addArtist(artist) {
        this.artists.push(artist);
    }

    addRiderElement(artist, riderElement) {
        this.riderElements.push([artist, riderElement]);
    }

    static getTestEvents() {
        let eventOne = new Event(0, 'Festival4evah',
            '20210101', '20220101', '0000', '0000',
            null, null, null,
            0, 'Some festival',
            null, null,
            Organizer.getTestOrganizer()[0], 1,
            'eventImage.png');

        eventOne.addCrewCategory('Lazy Work');
        eventOne.addCrewCategory('Important Work (empty)');

        eventOne.addArtist(Artist.getTestArtists()[0]);
        eventOne.addArtist(Artist.getTestArtists()[1]);

        eventOne.addRiderElement(eventOne.artists[0], RiderElement.getTestRiderElement()[0]);
        eventOne.addRiderElement(eventOne.artists[1], RiderElement.getTestRiderElement()[1]);
        return [eventOne];
    }

    getRiderFromArtist(artist) {
        return this.riderElements.filter(riderElement =>riderElement[0].artistID === artist.artistID)
            .map(riderElement => riderElement[1]);
    }

    toString() {
        return "Name: " + this.eventName +
            "\nstartDate : " + this.startDate +
            "\nendDate: " + this.endDate +
            "\nstarttime: " + this.startTime +
            "\nendtime: " + this.endTime +
            "\naddress:  " + this.address +
            "\ntown: " + this.town +
            "\nzip: " + this.zipCode +
            "\nstatus: " + this.status +
            "\ndesc: " + this.description +
            "\nPublishDate: " + this.publishDate +
            "\nPublishTime: " + this.publishTime +
            "\nOrganizer: " + this.organizer +
            "\nType: " + this.eventType +
            "\nPic: " + this.picture;
    }

}