/**
 * @classdesc Utility class for connecting a picture ID to a link to that picture.
 */
export class PictureElement {
    /**
     *
     * @param {int}pictureID
     * The ID of a picture. Generated by the database.
     * @param {String}pictureLink
     * The link to where the picture is saved.
     */
    constructor(pictureID, pictureLink) {
        this.pictureID = pictureID;
        this.pictureLink = pictureLink;
    }
}